- hosts: all
  become: true
  tasks:


  - name: install httpd and php package
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: true
    when: ansible_distribution in ["Fedora", "Centos", "Rocky"]

  - name: install apache package
    apt:
      name: 
        - apache2
        - php
      state: latest
      update_cache: true
    when: ansible_distribution in ["Debian", "Ubuntu"]
