- hosts: web_servers
  become: true
  tasks:

  - name: install update
    tags: apache, httpd, php, update, web
    dnf:
      name:
        - httpd
        - php
      state: present
      update_cache: true
    when: ansible_distribution in ["Fedora", "Centos", "Rocky"]

- hosts: db_servers
  become: true
  pre_tasks:

  - name: install mariadb
    tags: db, mariadb
    dnf:
      name: mariadb
      state: present
      update_cache: true
    when: ansible_distribution in ["Fedora", "Centos", "Rocky"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba
    tags: file, smaba
    dnf:
      name: samba
      state: present
      update_cache: true
    when: ansible_distribution in ["Fedora", "Centos", "Rocky"]
