- name: install httpd package
  tags: apache,httpd,php,rocky
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: present
  when: ansible_distribution == "Rocky"

- name: start httpd service
  tags: httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
  when: ansible_distribution == "Rocky"
    
- name: copy default html file for site
  tags: apache,httpd
  copy:
    src: default.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
    
- name: change email address for admin
  tags: httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.xyz
  when: ansible_distribution == "Rocky"
  notify: restart_apache

