- name: install unzip
  package:
    name: unzip

- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_386.zip
    dest: /usr/local/bin
    remote_src: true
    mode: 0755
    owner: root
    group: root
